version: '3.5'
services:

  mysql: 
    image: mysql:5.7
    restart: always
    hostname: ${PROJECT_NAME}_mysql
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}' # TODO: Change this
      MYSQL_DATABASE: '${DB_NAME}'
    ports:
      - 3306:3306 
    volumes:
      - './database-init:/docker-entrypoint-initdb.d'