version: '3.5'
services:
  node:
    image: node:alpine
    restart: always
    container_name: ${PROJECT_NAME}_node
    env_file:
      - ./.env
    ports:
      - ${PORT}:7001
    volumes:
      - '.:/data'
    working_dir: /data
    command: sh -c "yarn && npm run docker"
    depends_on:
      - ${DB_HOST}
  mysql: 
    image: mysql:5.7
    restart: always
    hostname: ${PROJECT_NAME}_mysql
    container_name: ${PROJECT_NAME}_mysql
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:3306 
    volumes:
      - './data:/var/lib/mysql'
      - './mysql:/docker-entrypoint-initdb.d'