version: '3.5'
services:

  node:
    image: node:alpine
    restart: always
    container_name: ${PROJECT_NAME}_node
    environment:
      NODE_ENV: 'production'
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - ${PORT}:7001
    volumes:
      - '.:/data'
    working_dir: /data
    command: sh -c "npm run sql:init"
    depends_on:
      - mysql

  mysql: 
    image: mysql:5.7
    restart: always
    hostname: ${PROJECT_NAME}_mysql
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}' # TODO: Change this
    ports:
      - 3306:3306 
    volumes:
      - './database-init:/docker-entrypoint-initdb.d'